version: '2'

services:
    pdf_to_ebinterface:
        image: 752277495799.dkr.ecr.eu-west-1.amazonaws.com/pdf-to-ebinterface:latest
        # 256 mb
        mem_limit: 268435456
        privileged: true
        ports:
          - "8844:80"
